language: ruby

sudo: required

cache: bundler

rvm:
  - 2.5.0

addons:
  postgresql: '9.6'
  chrome: stable

env:
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_DB: 12
  RAILS_ENV: test

services:
  - postgresql
  - redis-server

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:test:prepare
  - bundle exec rake assets:precompile

script: bundle exec rspec spec/

after_success:
  - bundle exec codeclimate-test-reporter
