language: ruby

cache: bundler

rvm:
  - 2.4.0

addons:
  postgresql: '9.6'

env:
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_DB: 12
  RAILS_ENV: test

services:
  - postgresql
  - redis-server

before_install:
  - "phantomjs --version"
  - "mkdir travis-phantomjs && PHANTOM_EXISTS=false"
  - "if [ $PHANTOM_EXISTS = 'false' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $PHANTOM_EXISTS = 'false' ]; then tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs; fi"
  - "export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "phantomjs --version"

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:test:prepare
  - bundle exec rake assets:precompile

script: bundle exec rspec spec/

after_success:
  - bundle exec codeclimate-test-reporter
