version: '2'

services:
  db:
    image: postgres:9.5.2
    environment:
      POSTGRES_PASSWORD: &DB_PASSWORD tracks-tracks
      POSTGRES_USER: &DB_USERNAME skyderby
      POSTGRES_DB: &DB_NAME skyderby
    ports:
      - "5432:5432"
    volumes:
    - data_pg:/var/lib/postgresql/data
    container_name: skyderby_db

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment: &ENV
      DB_NAME: *DB_NAME
      DB_HOST: db
      DB_USERNAME: *DB_USERNAME
      DB_PASSWORD: *DB_PASSWORD
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 12
    volumes:
      - ./:/opt/app
    links:
      - db
      - redis
    ports:
      - "3000:3000"
    container_name: skyderby_app

  workers:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      <<: *ENV
    volumes:
      - ./:/opt/app
    links:
      - db
      - redis
    command: "bundle exec sidekiq"
    container_name: skydebry_workers

  redis:
    image: redis:3.0.5
    volumes:
      - data_redis:/data
    container_name: skyderby_redis

volumes:
  data_pg:
    external: true
  data_redis:
    external: true
